# Generated by Django 5.2.7 on 2026-02-04 11:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def remove_duplicate_participants(apps, schema_editor):
    """إزالة المشاركين المكررين (influencer_id, phone) قبل إضافة القيد الفريد"""
    Participant = apps.get_model('influencers', 'Participant')
    seen = set()
    to_delete = []
    for p in Participant.objects.order_by('id'):
        key = (p.influencer_id, str(p.phone) if p.phone else '')
        if key in seen:
            to_delete.append(p.id)
        else:
            seen.add(key)
    Participant.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_participant'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_participants, migrations.RunPython.noop),
        migrations.CreateModel(
            name='InfluencerWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=255, verbose_name='الجائزة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الفوز')),
            ],
            options={
                'verbose_name': 'فائز (مؤثر)',
                'verbose_name_plural': 'الفائزون (مؤثرين)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, verbose_name='رقم الجوال'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('influencer', 'phone'), name='unique_influencer_phone'),
        ),
        migrations.AddField(
            model_name='influencerwinner',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='influencers.influencer', verbose_name='المؤثر'),
        ),
        migrations.AddField(
            model_name='influencerwinner',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='influencers.participant', verbose_name='الفائز'),
        ),
    ]
