# Generated by Django 5.2.7 on 2026-08-30 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_add_visitor_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeapWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='عند التفعيل تظهر صفحة العجلة للعملاء على الرابط العام', verbose_name='تفعيل العجلة')),
                ('title', models.CharField(default='عجلة LEAP', max_length=200, verbose_name='عنوان العجلة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'عجلة LEAP',
                'verbose_name_plural': 'عجلة LEAP',
            },
        ),
        migrations.CreateModel(
            name='LeapWheelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجائزة')),
                ('total_quantity', models.PositiveIntegerField(default=1, help_text='عدد مرات ظهور هذه الجائزة في المخزون', verbose_name='الكمية الإجمالية')),
                ('remaining_quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية المتبقية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('leap_wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='game.leapwheel', verbose_name='عجلة LEAP')),
            ],
            options={
                'verbose_name': 'جائزة LEAP',
                'verbose_name_plural': 'جوائز LEAP',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeapWheelSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('visitor_phone', models.CharField(max_length=15, verbose_name='رقم الجوال')),
                ('prize_name', models.CharField(max_length=200, verbose_name='اسم الجائزة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='المتصفح')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدورة')),
                ('leap_wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='game.leapwheel', verbose_name='عجلة LEAP')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spins', to='game.leapwheelprize', verbose_name='الجائزة')),
            ],
            options={
                'verbose_name': 'دورة LEAP',
                'verbose_name_plural': 'دورات LEAP',
                'ordering': ['-created_at'],
            },
        ),
    ]
