# Generated by Django 5.2.7 on 2026-08-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_leap_wheel'),
    ]

    operations = [
        migrations.AddField(
            model_name='leapwheel',
            name='center_label',
            field=models.CharField(blank=True, default='RE9LOV', max_length=100, verbose_name='نص مركز العجلة'),
        ),
        migrations.AddField(
            model_name='leapwheel',
            name='center_logo',
            field=models.ImageField(blank=True, null=True, upload_to='leap_wheel/center/', verbose_name='شعار مركز العجلة'),
        ),
        migrations.AddField(
            model_name='leapwheel',
            name='sponsor_1_logo',
            field=models.ImageField(blank=True, null=True, upload_to='leap_wheel/sponsors/', verbose_name='شعار الراعي 1'),
        ),
        migrations.AddField(
            model_name='leapwheel',
            name='sponsor_1_name',
            field=models.CharField(blank=True, default='Badie', max_length=120, verbose_name='الراعي الاستراتيجي 1'),
        ),
        migrations.AddField(
            model_name='leapwheel',
            name='sponsor_2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='leap_wheel/sponsors/', verbose_name='شعار الراعي 2'),
        ),
        migrations.AddField(
            model_name='leapwheel',
            name='sponsor_2_name',
            field=models.CharField(blank=True, default='Poco Dor CHOCOLATIER', max_length=120, verbose_name='الراعي الاستراتيجي 2'),
        ),
        migrations.AddField(
            model_name='leapwheelprize',
            name='logo',
            field=models.ImageField(blank=True, help_text='يظهر على شريحة العجلة — ارفع شعار الشريك من التصميم', null=True, upload_to='leap_wheel/prizes/', verbose_name='شعار الشريك'),
        ),
        migrations.AlterField(
            model_name='leapwheel',
            name='title',
            field=models.CharField(default='العجلة المشتركة', max_length=200, verbose_name='عنوان العجلة'),
        ),
        migrations.AlterField(
            model_name='leapwheelprize',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الجائزة / الشريك'),
        ),
    ]
