# Generated by Django 5.2.7 on 2026-08-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_leap_wheel_shared_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leapwheel',
            name='center_label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نص مركز العجلة'),
        ),
    ]
