# Generated by Django 5.2.11 on 2026-09-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_add_re9lov_prize'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leapwheelspin',
            constraint=models.UniqueConstraint(fields=('leap_wheel', 'visitor_phone'), name='unique_leap_wheel_phone'),
        ),
    ]
